name: Plugin CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  plugin-ci:
    uses:  outoftheboxplugins/BuildMachines/.github/workflows/compile-plugin.yml@master
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
